name: Get/Update Primer Color Primitives

env:
  _DEST: '${{ github.workspace }}/lua/github-theme/palette/primitives'
  _JSON_DIR: '${{ github.workspace }}/node_modules/@primer/primitives/dist/json/colors'
  _LICENSE_GLOB: '${{ github.workspace }}/node_modules/@primer/primitives/[Ll][Ii][Cc][Ee][Nn][Ss][Ee]*'

on:
  workflow_dispatch:
  schedule:
    # 3x per week (every other day) at 12:40pm Pacific Time
    - cron: '40 19 * * 1,3,5'

jobs:
  get-colors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        # with:
        #   cache: npm

      - run: npm i @primer/primitives@latest

      - run: |
          set -u +f
          shopt -s nocaseglob failglob
          license="$(<$_LICENSE_GLOB)"
          mkdir -p "$_DEST"
          cd "$_JSON_DIR"

          for file in *.json; do
            cat >"${_DEST_DIR}/${file%.json}.lua" <<EOF
          local M = vim.json.decode([=[$(<"$file")]=], { luanil = { object = false, array = false } })
          M._LICENSE = [=[$license]=]
          return M
          EOF
          done

      - run: make fmt

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update color primitives
          branch: update-color-primitives
          delete-branch: true
          title: Update color primitives
